
CREATE TABLESPACE BARERESTAURANTE
DATAFILE
'C:\ORACLE\BARERESTAURANTE.dbf'
SIZE 100m AUTOEXTEND ON NEXT 50M MAXSIZE 500M
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
SEGMENT SPACE MANAGEMENT AUTO;
 
ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;

CREATE USER USUARIO_BARERESTAURANTE
IDENTIFIED BY 021021
DEFAULT TABLESPACE BARERESTAURANTE
TEMPORARY TABLESPACE TEMP;


GRANT CREATE SESSION,CONNECT,RESOURCE TO USUARIO_BARERESTAURANTE;

ALTER USER USUARIO_BARERESTAURANTE QUOTA UNLIMITED ON BARERESTAURANTE;


CREATE TABLE USUARIO 
(ID_USUARIO INTEGER NOT NULL,
LOGIN VARCHAR2(20),
SENHA VARCHAR2(10),
CONSTRAINT ID_USUARIO_PK PRIMARY KEY(ID_USUARIO));

CREATE SEQUENCE USUARIO_SEQ
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;

 
INSERT INTO USUARIO (ID_USUARIO,LOGIN,SENHA) VALUES (USUARIO_SEQ.NEXTVAL, 'ADMINISTRADOR', 'ADM123');

INSERT INTO USUARIO (ID_USUARIO,LOGIN,SENHA) VALUES (USUARIO_SEQ.NEXTVAL, 'USUARIO1', 'USER123');

INSERT INTO USUARIO (ID_USUARIO,LOGIN,SENHA) VALUES (USUARIO_SEQ.NEXTVAL, 'USUARIO2', 'USER2020');


CREATE TABLE CATEGORIA 
(ID_CATEGORIA INTEGER NOT NULL,
CATEGORIA VARCHAR2(50),
CONSTRAINT ID_CATEGORIA_PK PRIMARY KEY(ID_CATEGORIA));


CREATE SEQUENCE CATEGORIA_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

INSERT INTO CATEGORIA (ID_CATEGORIA, CATEGORIA) VALUES (CATEGORIA_SEQ.NEXTVAL,'Bebida');

INSERT INTO CATEGORIA (ID_CATEGORIA,CATEGORIA) VALUES (CATEGORIA_SEQ.NEXTVAL,'Porção');

INSERT INTO CATEGORIA (ID_CATEGORIA, CATEGORIA) VALUES (CATEGORIA_SEQ.NEXTVAL,'Self-Service');


CREATE TABLE EXCECOES
(ID_EXCECOES INTEGER NOT NULL,
NOME VARCHAR2(20),
CONSTRAINT ID_EXCECOES_PK PRIMARY KEY(ID_EXCECOES));


CREATE SEQUENCE EXCECOES_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

INSERT INTO EXCECOES (ID_EXCECOES,NOME) VALUES (EXCECOES_SEQ.NEXTVAL,'Limaão');

INSERT INTO EXCECOES (ID_EXCECOES,NOME) VALUES (EXCECOES_SEQ.NEXTVAL,'Gelo');

INSERT INTO EXCECOES (ID_EXCECOES,NOME) VALUES (EXCECOES_SEQ.NEXTVAL,'Cheddar');

CREATE TABLE PRODUTO
(ID_PRODUTO INTEGER NOT NULL,
NOME VARCHAR2(50),
DESCRICAO VARCHAR2(50),
ID_CATEGORIA INTEGER NOT NULL,
PRECO DECIMAL(10,2),
CONSTRAINT ID_PRODUTO_PK PRIMARY KEY(ID_PRODUTO),
CONSTRAINT ID_CATEGORIA_FK FOREIGN KEY(ID_CATEGORIA) REFERENCES CATEGORIA (ID_CATEGORIA));


CREATE SEQUENCE PRODUTO_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;


INSERT INTO PRODUTO(ID_PRODUTO,NOME,DESCRICAO,ID_CATEGORIA,PRECO) VALUES (PRODUTO_SEQ.NEXTVAL,'Água','Garrafa 350ML',1,2.00);

INSERT INTO PRODUTO(ID_PRODUTO,NOME,DESCRICAO,ID_CATEGORIA,PRECO) VALUES (PRODUTO_SEQ.NEXTVAL,'Coca-Cola','Lata',1,5.00);

INSERT INTO PRODUTO(ID_PRODUTO,NOME,DESCRICAO,ID_CATEGORIA,PRECO) VALUES (PRODUTO_SEQ.NEXTVAL,'Tilápia','500g',2,20.00);

INSERT INTO PRODUTO(ID_PRODUTO,NOME,DESCRICAO,ID_CATEGORIA,PRECO) VALUES (PRODUTO_SEQ.NEXTVAL,'Almoço','Almoço com Churrasco',3,39.90);



CREATE TABLE CLIENTE
(ID_CLIENTE INTEGER NOT NULL,
NOME VARCHAR2(50) NOT NULL,
CPF VARCHAR2(11)NOT NULL,
CONSTRAINT ID_CLIENTE_PK PRIMARY KEY(ID_CLIENTE));


CREATE SEQUENCE CLIENTE_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

INSERT INTO CLIENTE (ID_CLIENTE,NOME,CPF) VALUES (CLIENTE_SEQ.NEXTVAL,'Maria','11235865908');

INSERT INTO CLIENTE (ID_CLIENTE,NOME,CPF) VALUES (CLIENTE_SEQ.NEXTVAL,'José','00865974589');

INSERT INTO CLIENTE (ID_CLIENTE,NOME,CPF) VALUES (CLIENTE_SEQ.NEXTVAL,'Pedro','00152963478');



CREATE TABLE PEDIDOS 
(ID_PEDIDOS INTEGER NOT NULL,
OBSERVACAO VARCHAR2(1000),
ID_CLIENTE INTEGER NOT NULL,
CONSTRAINT ID_PEDIDOS_PK PRIMARY KEY(ID_PEDIDOS),
CONSTRAINT ID_CLIENTE_FK FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE));




CREATE SEQUENCE PEDIDOS_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

INSERT INTO PEDIDOS (ID_PEDIDOS,ID_CLIENTE) VALUES (PEDIDOS_SEQ.NEXTVAL,1);

INSERT INTO PEDIDOS (ID_PEDIDOS,ID_CLIENTE) VALUES (PEDIDOS_SEQ.NEXTVAL,2);

INSERT INTO PEDIDOS (ID_PEDIDOS,ID_CLIENTE) VALUES (PEDIDOS_SEQ.NEXTVAL,3);



CREATE TABLE PRODUTOS_PEDIDOS
(ID_PRODUTO_PEDIDO INTEGER NOT NULL,
QUANTIDADE NUMBER(10,2),
ID_PEDIDOS INTEGER NOT NULL,
ID_PRODUTO INTEGER NOT NULL,
CONSTRAINT ID_PRODUTO_PEDIDO_PK PRIMARY KEY(ID_PRODUTO_PEDIDO),
CONSTRAINT ID_PEDIDOS_FK FOREIGN KEY(ID_PEDIDOS) REFERENCES PEDIDOS(ID_PEDIDOS),
CONSTRAINT ID_PRODUTO_FK FOREIGN KEY(ID_PRODUTO) REFERENCES PRODUTO(ID_PRODUTO));

 
    
CREATE SEQUENCE PRODUTOS_PEDIDOS_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;


INSERT INTO PRODUTOS_PEDIDOS(ID_PRODUTO_PEDIDO,QUANTIDADE,ID_PEDIDOS,ID_PRODUTO) VALUES (PRODUTOS_PEDIDOS_SEQ.NEXTVAL,1.00,1,1);

INSERT INTO PRODUTOS_PEDIDOS(ID_PRODUTO_PEDIDO,QUANTIDADE,ID_PEDIDOS,ID_PRODUTO) VALUES (PRODUTOS_PEDIDOS_SEQ.NEXTVAL,5.00,1,2);

INSERT INTO PRODUTOS_PEDIDOS(ID_PRODUTO_PEDIDO,QUANTIDADE,ID_PEDIDOS,ID_PRODUTO) VALUES (PRODUTOS_PEDIDOS_SEQ.NEXTVAL,2.00,1,4);

INSERT INTO PRODUTOS_PEDIDOS(ID_PRODUTO_PEDIDO,QUANTIDADE,ID_PEDIDOS,ID_PRODUTO) VALUES (PRODUTOS_PEDIDOS_SEQ.NEXTVAL,3.00,2,1);

INSERT INTO PRODUTOS_PEDIDOS(ID_PRODUTO_PEDIDO,QUANTIDADE,ID_PEDIDOS,ID_PRODUTO) VALUES (PRODUTOS_PEDIDOS_SEQ.NEXTVAL,1.00,2,2);

INSERT INTO PRODUTOS_PEDIDOS(ID_PRODUTO_PEDIDO,QUANTIDADE,ID_PEDIDOS,ID_PRODUTO) VALUES (PRODUTOS_PEDIDOS_SEQ.NEXTVAL,2.00,2,3);

INSERT INTO PRODUTOS_PEDIDOS(ID_PRODUTO_PEDIDO,QUANTIDADE,ID_PEDIDOS,ID_PRODUTO) VALUES (PRODUTOS_PEDIDOS_SEQ.NEXTVAL,2.00,3,1);

INSERT INTO PRODUTOS_PEDIDOS(ID_PRODUTO_PEDIDO,QUANTIDADE,ID_PEDIDOS,ID_PRODUTO) VALUES (PRODUTOS_PEDIDOS_SEQ.NEXTVAL,4.00,3,2);

INSERT INTO PRODUTOS_PEDIDOS(ID_PRODUTO_PEDIDO,QUANTIDADE,ID_PEDIDOS,ID_PRODUTO) VALUES (PRODUTOS_PEDIDOS_SEQ.NEXTVAL,1.00,3,3);



CREATE TABLE EXCECOES_PRODUTOS_PEDIDOS
(ID_EXCECOES_PRODUTOS_PEDIDOS INTEGER NOT NULL,
ID_PRODUTO INTEGER NOT NULL,
ID_PEDIDOS INTEGER NOT NULL,
ID_EXCECOES INTEGER NOT NULL,
CONSTRAINT ID_EXCECOES_PRODUTOS_PEDIDOS_PK PRIMARY KEY(ID_EXCECOES_PRODUTOS_PEDIDOS),
CONSTRAINT ID_EXCECOES_PRODUTO_FK FOREIGN KEY(ID_PRODUTO) REFERENCES PRODUTO (ID_PRODUTO),
CONSTRAINT ID_EXCECOES_PEDIDOS_FK FOREIGN KEY(ID_PEDIDOS) REFERENCES PEDIDOS (ID_PEDIDOS),
CONSTRAINT ID_EXCECOES_EXECOES_FK FOREIGN KEY(ID_EXCECOES) REFERENCES EXCECOES (ID_EXCECOES));



CREATE SEQUENCE EXCEXOES_PRODUTOS_PEDIDOS_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

INSERT INTO EXCECOES_PRODUTOS_PEDIDOS (ID_EXCECOES_PRODUTOS_PEDIDOS,ID_PRODUTO,ID_PEDIDOS, ID_EXCECOES) VALUES (EXCEXOES_PRODUTOS_PEDIDOS_SEQ.NEXTVAL,2,2,1);

INSERT INTO EXCECOES_PRODUTOS_PEDIDOS (ID_EXCECOES_PRODUTOS_PEDIDOS,ID_PRODUTO,ID_PEDIDOS, ID_EXCECOES) VALUES (EXCEXOES_PRODUTOS_PEDIDOS_SEQ.NEXTVAL,2,2,2);

INSERT INTO EXCECOES_PRODUTOS_PEDIDOS (ID_EXCECOES_PRODUTOS_PEDIDOS,ID_PRODUTO,ID_PEDIDOS, ID_EXCECOES) VALUES (EXCEXOES_PRODUTOS_PEDIDOS_SEQ.NEXTVAL,3,3,3);



SELECT PE.ID_PEDIDOS,CL.ID_CLIENTE,CL.NOME as CLIENTE,PP.ID_PRODUTO_PEDIDO,P.ID_PRODUTO,P.NOME,P.DESCRICAO,C.CATEGORIA,PP.QUANTIDADE,PE.OBSERVACAO,P.PRECO
FROM PEDIDOS PE 
JOIN CLIENTE CL ON CL.ID_CLIENTE = PE.ID_CLIENTE
JOIN PRODUTOS_PEDIDOS PP ON PP.ID_PEDIDOS = PE.ID_PEDIDOS
JOIN PRODUTO P ON PP.ID_PRODUTO = P.ID_PRODUTO
JOIN CATEGORIA C ON P.ID_CATEGORIA = C.ID_CATEGORIA
ORDER BY PE.ID_PEDIDOS ASC, PP.ID_PRODUTO_PEDIDO ASC;


